alias gd="git diff --ignore-all-space"
alias gds="git diff --ignore-all-space --staged"
alias gs="git status"
alias gprune="git remote prune origin"
alias gdryprune="git remote prune origin --dry-run"
